### ISSUE TITLE
Add patch for Breathedge 60FPS

### ISSUE THREAD

**Issue by Medekaisa** [masagrator/FPSLocker-Warehouse#754]
Hello! Is it possible to request an update for the latest version of Breathedge, v1.0.2?

TID:01000AA013A5E000
BID:B26DE1669B729335

Thank you!

**Comment by masagrator** [comment]
Use
https://github.com/masagrator/UE4cfgdumper

And send me generated log file.

**Comment by Medekaisa** [comment]
Please check the file

[B26DE1669B729335.log](https://github.com/user-attachments/files/19535000/B26DE1669B729335.log)

**Comment by masagrator** [comment]
From what I see, this game doesn't use internal FPS Lock (though GameStruct dump failed, so it's not a given) nor has Dynamic Resolution. Only r.VSync is used thay may have hindered performance.

```yaml
# Breathedge 1.0.2
# BID: B26DE1669B729335

unsafeCheck: true

ALL_FPS:
  # t.MaxFPS
  -
    type: evaluate_write
    address: [MAIN, 0x55CBDE0, 0]
    value_type: float
    value: [FPS_LOCK_TARGET, FPS_LOCK_TARGET]
  # r.VSync
  -
    type: write
    address: [MAIN, 0x4E6A7B8, 0]
    value_type: uint32
    value: [0, 0]
  -
    type: block
    what: timing
```
For tests
